### ISSUE TITLE
DHCP Broadcast not passed through

### ISSUE THREAD

**Issue by ben-oxley** [halmartin/meraki-builder#13]
Whilst I've not fully tested this yet, I seem to see a weird behaviour when following these steps:

1. Connect DHCP Server and upstream network to Port 1.
2. Boot up MS220-8P
3. Connect POE powered device (MR-18 flashed with OpenWRT) to Port 2.
4. Device on port 2 does not acquire an IP address.

I suspect that either the switch is not passing on DHCP packets or probably more likely isn't forwarding broadcast packets?

I'll continue to investigate with some wireshark etc.

**Comment by halmartin** [comment]
Can you MITM the upstream network port of the MS220-8P and see if you see the `DHCPREQUEST` from the MR-18?

I have not had any issues with downstream devices obtaining a DHCP lease on my MS220-8P.

**Comment by ben-oxley** [comment]
Will do! I'll get back to you with it, as soon as I can get something to MITM the traffic.

**Comment by halmartin** [comment]
You don't need to necessarily MITM the traffic, you can run `dnsmasq` (and optionally `tcpdump`) on the upstream device and you'll have a view of DHCP request/replies.

e.g. on the upstream device connected to the MS220:
```
ip addr add 192.168.10.1/24 dev eth0
dnsmasq -a 192.168.10.1 -d -F 192.168.10.10,192.168.10.20,2h -i eth0
```

dnsmasq will then show `DHCPDISCOVER`, `DHCPOFFER`, `DHCPREQUEST`, and `DHCPACK` in stdout. Replace eth0 with your Ethernet interface device name.

**Comment by ben-oxley** [comment]
I don't have the results of a tcpdump/similar for you yet, but check this out. The issue turns out to only be on port 2 of the switch its possible that it isn't just DNS but all traffic. It's possible that its just a dodgy port. I've got another switch that I need to flash at some point soon so I'll try that and see if it has the same problem and report back.

**Comment by halmartin** [comment]
This is the same switch you were having PoE issues on, right? If I remember correctly, you said that you tried other ports and PoE was still non-functional, so there may indeed be something wrong with the 220-48LP.

It's strange though, because I would expect the same issues on the 320-48LP/FP, and other people have not reported any issues with these models. The only differences I know of between the 220-48 and 320-48 are the hot-swap power supplies.

What does `/click/switch_port_table/dump_pports` say when you have a device connected to port 2? I assume the port is at least negotiating a link.

It might also be worth taking a look at `/click/switch_port_table/dump_pport_vlans`; maybe I've got an error in an initscript and the port is not being initialized on VLAN/PVID 1.

**Comment by ben-oxley** [comment]
Sorry no, this is on an MS220-8P (not 48).

I'll take a look at the dump_pports tomorrow and see what it says.

**Comment by ben-oxley** [comment]
Seems to be a dodgy port on the 8p, just flashed a second one and port works just fine!
