### ISSUE TITLE
MS320-48 fails on first boot "failed back to cpuinfo board detection" Does not detect model number

### ISSUE THREAD

**Issue by JustinBa** [halmartin/meraki-builder#17]
Hey, just tried to drop the firmware on one of my MS320-48's and the system was unable to fully boot. It appears to me that it was unable to read the model number from the system.

Is there anything that I can try to get auto detection to work? If not I might try to see if I can roll my own version that bypasses the detection and just jumps past with the proper values.

 Boot log is as follows.
```
⸮LinuxLoader built Nov 12 2020 18:01:50
init_pll ok
init_spi ok
init_memctl ok
wait_memctl ok
Training DRAM ok
init_irq ok
init_dram_uncached ok
init_icache ok
init_dcache ok
enable_caches ok
init_pi ok
init_board ok
Low level initialization complete, exiting boot mode
[    0.000000] Linux version 3.18.123-meraki-elemental (hmartin@alp) (gcc version 5.4.0 (GCC) ) #10 Sat Jul 18 17:06:37 UTC 2020
[    0.000000] CPU0 revision is: 01019654 (MIPS 24KEc)
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 00477000 @ 00100000 (usable)
[    0.000000]  memory: 00049000 @ 00577000 (usable after init)
[    0.000000] User-defined physical RAM map:
[    0.000000]  memory: 07ff0000 @ 00000000 (usable)
[    0.000000] Initmem setup node 0 [mem 0x00000000-0x07feffff]
[    0.000000] Reserving 0MB of memory at 0MB for crashkernel
[    0.000000] Kernel command line: console=ttyS0,115200 mtdparts=m25p80:0x40000(redboot),0x2c0000(kernel),0x800000(squashfs),0x500000(overlay) root=/dev/mtdblock3 ubi.mtd=gen_nand.0 mem=134152192
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Writing ErrCtl register=8006e000
[    0.000000] Readback ErrCtl register=8006e000
[    0.000000] Cache parity protection enabled
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:66
[    0.000000] sched_clock: 32 bits at 1kHz, resolution 1000000ns, wraps every 2147483648000000ns
[    0.002000] VCore-III slave device ID 7460 found
[    0.002000] Calibrating delay loop... 275.45 BogoMIPS (lpj=137728)
[    0.011000] pid_max: default: 32768 minimum: 301
[    0.011000] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.011000] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.013000] ftrace: allocating 11994 entries in 24 pages
[    0.041000] Performance counters: mips/24K PMU enabled, 2 32-bit counters available to each CPU, irq -1 (share with timer interrupt)
[    0.048000] devtmpfs: initialized
[    0.055000] NET: Registered protocol family 16
[    0.094000] Switched to clocksource MIPS
[    0.124000] NET: Registered protocol family 2
[    0.127000] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.128000] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.128000] TCP: Hash tables configured (established 1024 bind 1024)
[    0.128000] TCP: reno registered
[    0.128000] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.128000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.129000] NET: Registered protocol family 1
[    0.133000] VCORE-III Watchdog Timer enabled (30 seconds).  Prev boot was not caused by WDT reset.
[    0.158000] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.195000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.195000] jffs2: version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
[    0.198000] msgmni has been set to 241
[    0.226000] io scheduler noop registered
[    0.226000] io scheduler deadline registered (default)
[    0.228000] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.230000] console [ttyS0] disabled
[    0.231000] serial8250.0: ttyS0 at MMIO 0x70100000 (irq = 14, base_baud = 13020833) is a 16550A
[    0.612000] console [ttyS0] enabled
[    0.622000] nand: device found, Manufacturer ID: 0x2c, Chip ID: 0xf1
[    0.628000] nand: Micron MT29F1G08ABADAWP
[    0.632000] nand: 128MiB, SLC, page size: 2048, OOB size: 64
[    0.644000] Scanning device for bad blocks
[    0.670000] Bad eraseblock 211 at 0x000001a60000
[    0.768000] m25p80 spi0.1: found mx25l12805d, expected m25p80
[    0.774000] m25p80 spi0.1: mx25l12805d (16384 Kbytes)
[    0.779000] 4 cmdlinepart partitions found on MTD device m25p80
[    0.785000] Creating 4 MTD partitions on "m25p80":
[    0.790000] 0x000000000000-0x000000040000 : "redboot"
[    0.810000] 0x000000040000-0x000000300000 : "kernel"
[    0.820000] 0x000000300000-0x000000b00000 : "squashfs"
[    0.835000] 0x000000b00000-0x000001000000 : "overlay"
[    0.849000] tun: Universal TUN/TAP device driver, 1.6
[    0.855000] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    0.864000] i2c /dev entries driver
[    0.871000] TCP: cubic registered
[    0.874000] Initializing XFRM netlink socket
[    0.882000] NET: Registered protocol family 10
[    0.891000] NET: Registered protocol family 17
[    0.896000] NET: Registered protocol family 15
[    0.900000] 8021q: 802.1Q VLAN Support v1.8
[    0.911000] i2c-gpio i2c-gpio.1: using pins 15 (SDA) and 14 (SCL)
[    0.917000] at24 1-0051: 1024 byte 24c08 EEPROM, writable, 8 bytes/write
[    0.926000] meraki-config meraki-config: Meraki config device loaded
[    1.063000] i2c-gpio i2c-gpio.2: using pins 708 (SDA) and 709 (SCL)
[    1.118000] i2c-gpio i2c-gpio.3: using pins 714 (SDA) and 715 (SCL)
[    1.174000] i2c-gpio i2c-gpio.4: using pins 720 (SDA) and 721 (SCL)
[    1.231000] i2c-gpio i2c-gpio.5: using pins 726 (SDA) and 727 (SCL)
[    1.248000] tmp401 6-004c: Detected TI TMP411 chip
[    1.258000] i2c-gpio i2c-gpio.6: using pins 47 (SDA) and 46 (SCL)
[    1.276000] i2c-gpio i2c-gpio.7: using pins 51 (SDA) and 50 (SCL)
[    1.291000] i2c-gpio i2c-gpio.8: using pins 53 (SDA) and 52 (SCL)
[    1.300000] at24 2-0050: 256 byte 24c02 EEPROM, read-only, 0 bytes/write
[    1.307000] at24 3-0050: 256 byte 24c02 EEPROM, read-only, 0 bytes/write
[    1.314000] at24 4-0050: 256 byte 24c02 EEPROM, read-only, 0 bytes/write
[    1.322000] at24 5-0050: 256 byte 24c02 EEPROM, read-only, 0 bytes/write
[    1.335000] pca953x 6-0022: interrupt support not compiled in
[    1.352000] UBI: attaching mtd0 to ubi0
[    2.162000] UBI: scanning is finished
[    2.204000] UBI: attached mtd0 (name "gen_nand.0", size 128 MiB) to ubi0
[    2.211000] UBI: PEB size: 131072 bytes (128 KiB), LEB size: 129024 bytes
[    2.218000] UBI: min./max. I/O unit sizes: 2048/2048, sub-page size 512
[    2.225000] UBI: VID header offset: 512 (aligned 512), data offset: 2048
[    2.231000] UBI: good PEBs: 1023, bad PEBs: 1, corrupted PEBs: 0
[    2.237000] UBI: user volume: 12, internal volumes: 1, max. volumes count: 128
[    2.245000] UBI: max/mean erase counter: 2902/2040, WL threshold: 4096, image sequence number: 2124770675
[    2.255000] UBI: available PEBs: 407, total reserved PEBs: 616, PEBs reserved for bad PEB handling: 19
[    2.265000] UBI: background thread "ubi_bgt0d" started, PID 297
[    2.385000] devtmpfs: mounted
[    2.418000] VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
[    2.456000] devtmpfs: mounted
[    2.465000] Freeing unused kernel memory: 292K
[    6.415000] devpts: called with bogus options
Starting syslogd: OK
Starting klogd: OK
Running sysctl: OK
!!! IMPORTANT !!!
Falling back to cpuinfo board detection, your board model is: , please open an issue on github.com/halmartin/meraki-builder
!!! IMPORTANT !!!
[    8.792000] random: nonblocking pool is initialized
insmod: ERROR: could not load module /lib/modules//vtss_core.ko: No such file or directory
Loaded 'proclikefs.ko'
[   15.030000] click: starting router thread pid 471 (87b62900)
Loaded 'merakiclick.ko'
[   26.171000] elts_meraki: module license 'unspecified' taints kernel.
[   26.178000] Disabling lock debugging due to kernel taint
Loaded 'elts_meraki.ko'
insmod: ERROR: could not load module /lib/modules//vc_click.ko: No such file or directory
[   28.401000] unsatisfied requirement 'vc_click'
[   28.407000] click-config/switch/io-real/vitesse.click:26: unknown element class 'ToVitesse'
[   28.416000] click-config/switch/io-real/vitesse.click:31: unknown element class 'FromVitesse'
[   28.426000] click-config/switch/io-real/vitesse.click:59: unknown element class 'VitesseController'
[   28.753000] click-config/switch.template:74: While configuring 'switch_intf_table :: SwitchIntfTable':
[   28.763000]   SWITCH_HARDWARE: element type mismatch, expected SwitchHardwareIntf
[   28.774000] click-config/switch.template:1045: While configuring 'switch_port_table :: SwitchPortTable':
[   28.783000]   SWITCH_HARDWARE_INTERFACE: element type mismatch, expected SwitchHardwareIntf
[   28.815000] click-config/switch.template:58: While configuring 'l3_update_hardware :: UpdateHardwareTable':
[   28.825000]   SWITCH_HARDWARE_INTERFACE: element type mismatch, expected SwitchHardwareIntf
[   28.843000] click-config/switch.template:383: While configuring 'switch_rpc_server :: SwitchRPCServer':
[   28.853000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   28.863000] click-config/switch.template:566: While configuring 'CheckStackMaster@187 :: CheckStackMaster':
[   28.873000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   28.881000] click-config/switch.template:602: While configuring 'CheckStackMaster@235 :: CheckStackMaster':
[   28.891000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   28.900000] click-config/switch.template:633: While configuring 'switch_mrt :: MulticastRoutingTable':
[   28.909000]   SWITCH_HARDWARE_INTERFACE: element type mismatch, expected SwitchHardwareIntf
[   28.920000] click-config/switch.template:655: While configuring 'ospf_hello_inspector :: OspfHelloInspector':
[   28.931000]   SWITCH_HARDWARE_INTERFACE: element type mismatch, expected SwitchHardwareIntf
[   28.963000] click-config/switch.template:875: While configuring 'msstp_encap_inst :: MSSTPEncap':
[   28.972000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   28.984000] click-config/switch.template:930: While configuring 'IntraStackResolver@527 :: IntraStackResolver':
[   28.994000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   29.006000] click-config/switch.template:1072: While configuring 'igmp_table :: IGMPSnoopTable':
[   29.015000]   SWITCH_HARDWARE_INTERFACE: element type mismatch, expected SwitchHardwareIntf
[   29.024000] click-config/switch.template:1093: While configuring 'mld_table :: MLDSnoopTable':
[   29.033000]   SWITCH_HARDWARE_INTERFACE: element type mismatch, expected SwitchHardwareIntf
[   29.044000] click-config/switch.template:1125: While configuring 'msstp_decap :: MSSTPDecap':
[   29.053000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   29.066000] click-config/switch.template:1187: While configuring 'CheckStackMaster@664 :: CheckStackMaster':
[   29.076000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   29.083000] click-config/switch.template:1189: While configuring 'CheckStackMaster@669 :: CheckStackMaster':
[   29.093000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   29.101000] click-config/switch.template:1199: While configuring 'CheckStackMaster@680 :: CheckStackMaster':
[   29.111000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   29.118000] click-config/switch.template:1212: While configuring 'CheckStackMaster@693 :: CheckStackMaster':
[   29.128000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   29.138000] click-config/switch.template:1238: While configuring 'CheckStackMaster@726 :: CheckStackMaster':
[   29.148000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   29.159000] click-config/switch.template:1307: While configuring 'stp_check_master :: CheckStackMaster':
[   29.169000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   29.177000] click-config/switch.template:1320: While configuring 'lacp_check_master :: CheckStackMaster':
[   29.187000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   29.195000] click-config/switch.template:1409: While configuring 'udld :: UDLD':
[   29.203000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   29.213000] click-config/switch.template:1459: While configuring 'CheckStackMaster@861 :: CheckStackMaster':
[   29.223000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   29.311000] Router could not be initialized!
Default port count: 10
net.ipv4.ip_local_reserved_ports = 50000-50127
vc_click isn't loaded; aborting!
/etc/init.d/S11leds: line 8: can't create /click/sw0_ctrl/power_led_orange: nonexistent directory
/etc/init.d/S11leds: line 9: can't create /click/sw0_ctrl/power_led_green: nonexistent directory
Saving random seed: SKIP (read-only file system detected)
Starting network: OK
Starting chrony: Could not open configuration file /etc/chrony.conf : No such file or directory
FAIL
Starting dropbear sshd: OK

/ # 
```

**Comment by halmartin** [comment]
Hey, thanks for opening an issue.

To debug why board detection failed, can you please provide the output from the following commands?
```
cat /proc/mtd
```
There should be an mtd part called `board-config` present. Please send me the `strings` output of that mtdpart (email if you prefer, as it will contain your MAC address and serial number).

```
cat /proc/cpuinfo
```

You can fix the issue by doing the following:
```
echo MODEL=MS320-48 > /etc/boardinfo
reboot
```

The switch should boot and load the correct kernel modules.

**Comment by JustinBa** [comment]
Thanks for the quick response!

I also had the same issue with a MS220-48FP (had a small pile of 220's and 320's I couldn't licence) but in both cases I was able to use the echo command to fix the issue.

The requested outputs are on the way to your email.

Thanks again!

**Comment by halmartin** [comment]
Alright, since Meraki felt the need to name multiple products `meraki_elemental` I implemented logic to use the product code which _is_ unique to each model to do the detection. This makes things slightly cleaner in the initscript.

I will update the flashable image when I find some time.

**Comment by halmartin** [comment]
I generated and tested a new build based on buildroot 2021.02.8 on my MS220-8. I'll update the installation docs tomorrow. I'd be interested to know if the new initscript logic correctly identifies your MS320-48

**Comment by KFDCompiled** [comment]
New init script logic did not detect MS320-48FP

**Comment by halmartin** [comment]
> New init script logic did not detect MS320-48FP

Please provide the output of the bootlog.

**Comment by halmartin** [comment]
> Will do; but before I do, do you want me to try: `echo MODEL=MS320-48FP > /etc/boardinfo`

Doing so will override the automatic board detection, which is failing.

Could you please execute `board_data product_number` and `board_data model` and share the output?

**Comment by KFDCompiled** [comment]
Boot log:
`LinuxLoader built Nov 12 2020 18:01:50
init_pll ok
init_spi ok
init_memctl ok
wait_memctl ok
Training DRAM ok
init_irq ok
init_dram_uncached ok
init_icache ok
init_dcache ok
enable_caches ok
init_pi ok
init_board ok
Low level initialization complete, exiting boot mode
[    0.000000] Linux version 3.18.123-meraki-elemental (hmartin@alp) (gcc version 5.4.0 (GCC) ) #10 Sat Jul 18 17:06:37 UTC 2020
[    0.000000] CPU0 revision is: 01019654 (MIPS 24KEc)
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 00477000 @ 00100000 (usable)
[    0.000000]  memory: 00049000 @ 00577000 (usable after init)
[    0.000000] User-defined physical RAM map:
[    0.000000]  memory: 07ff0000 @ 00000000 (usable)
[    0.000000] Initmem setup node 0 [mem 0x00000000-0x07feffff]
[    0.000000] Reserving 0MB of memory at 0MB for crashkernel
[    0.000000] Kernel command line: console=ttyS0,115200 mtdparts=m25p80:0x40000(redboot),0x2c0000(kernel),0x800000(squashfs),0x500000(overlay) root=/dev/mtdblock3 ubi.mtd=gen_nand.0 mem=134152192
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Writing ErrCtl register=80040300
[    0.000000] Readback ErrCtl register=80040300
[    0.000000] Cache parity protection enabled
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:66
[    0.000000] sched_clock: 32 bits at 1kHz, resolution 1000000ns, wraps every 2147483648000000ns
[    0.002000] VCore-III slave device ID 7460 found
[    0.002000] Calibrating delay loop... 275.45 BogoMIPS (lpj=137728)
[    0.011000] pid_max: default: 32768 minimum: 301
[    0.011000] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.011000] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.013000] ftrace: allocating 11994 entries in 24 pages
[    0.041000] Performance counters: mips/24K PMU enabled, 2 32-bit counters available to each CPU, irq -1 (share with timer interrupt)
[    0.048000] devtmpfs: initialized
[    0.055000] NET: Registered protocol family 16
[    0.094000] Switched to clocksource MIPS
[    0.124000] NET: Registered protocol family 2
[    0.127000] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.128000] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.128000] TCP: Hash tables configured (established 1024 bind 1024)
[    0.128000] TCP: reno registered
[    0.128000] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.128000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.129000] NET: Registered protocol family 1
[    0.133000] VCORE-III Watchdog Timer enabled (30 seconds).  Prev boot was not caused by WDT reset.
[    0.158000] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.195000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.195000] jffs2: version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
[    0.198000] msgmni has been set to 241
[    0.226000] io scheduler noop registered
[    0.227000] io scheduler deadline registered (default)
[    0.228000] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.231000] console [ttyS0] disabled
[    0.231000] serial8250.0: ttyS0 at MMIO 0x70100000 (irq = 14, base_baud = 13020833) is a 16550A
[    0.611000] console [ttyS0] enabled
[    0.621000] nand: device found, Manufacturer ID: 0x2c, Chip ID: 0xf1
[    0.627000] nand: Micron MT29F1G08ABADAWP
[    0.632000] nand: 128MiB, SLC, page size: 2048, OOB size: 64
[    0.643000] Scanning device for bad blocks
[    0.761000] m25p80 spi0.1: found mx25l12805d, expected m25p80
[    0.767000] m25p80 spi0.1: mx25l12805d (16384 Kbytes)
[    0.772000] 4 cmdlinepart partitions found on MTD device m25p80
[    0.778000] Creating 4 MTD partitions on "m25p80":
[    0.783000] 0x000000000000-0x000000040000 : "redboot"
[    0.804000] 0x000000040000-0x000000300000 : "kernel"
[    0.814000] 0x000000300000-0x000000b00000 : "squashfs"
[    0.829000] 0x000000b00000-0x000001000000 : "overlay"
[    0.844000] tun: Universal TUN/TAP device driver, 1.6
[    0.849000] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    0.857000] i2c /dev entries driver
[    0.863000] TCP: cubic registered
[    0.867000] Initializing XFRM netlink socket
[    0.874000] NET: Registered protocol family 10
[    0.896000] NET: Registered protocol family 17
[    0.901000] NET: Registered protocol family 15
[    0.905000] 8021q: 802.1Q VLAN Support v1.8
[    0.919000] i2c-gpio i2c-gpio.1: using pins 15 (SDA) and 14 (SCL)
[    0.926000] at24 1-0051: 1024 byte 24c08 EEPROM, writable, 8 bytes/write
[    0.934000] meraki-config meraki-config: Meraki config device loaded
[    1.058000] i2c-gpio i2c-gpio.2: using pins 708 (SDA) and 709 (SCL)
[    1.113000] i2c-gpio i2c-gpio.3: using pins 714 (SDA) and 715 (SCL)
[    1.170000] i2c-gpio i2c-gpio.4: using pins 720 (SDA) and 721 (SCL)
[    1.228000] i2c-gpio i2c-gpio.5: using pins 726 (SDA) and 727 (SCL)
[    1.245000] tmp401 6-004c: Detected TI TMP411 chip
[    1.256000] i2c-gpio i2c-gpio.6: using pins 47 (SDA) and 46 (SCL)
[    1.273000] i2c-gpio i2c-gpio.7: using pins 51 (SDA) and 50 (SCL)
[    1.289000] i2c-gpio i2c-gpio.8: using pins 53 (SDA) and 52 (SCL)
[    1.297000] at24 2-0050: 256 byte 24c02 EEPROM, read-only, 0 bytes/write
[    1.305000] at24 3-0050: 256 byte 24c02 EEPROM, read-only, 0 bytes/write
[    1.312000] at24 4-0050: 256 byte 24c02 EEPROM, read-only, 0 bytes/write
[    1.319000] at24 5-0050: 256 byte 24c02 EEPROM, read-only, 0 bytes/write
[    1.332000] pca953x 6-0022: interrupt support not compiled in
[    1.349000] UBI: attaching mtd0 to ubi0
[    2.162000] UBI: scanning is finished
[    2.204000] UBI: attached mtd0 (name "gen_nand.0", size 128 MiB) to ubi0
[    2.211000] UBI: PEB size: 131072 bytes (128 KiB), LEB size: 129024 bytes
[    2.218000] UBI: min./max. I/O unit sizes: 2048/2048, sub-page size 512
[    2.225000] UBI: VID header offset: 512 (aligned 512), data offset: 2048
[    2.231000] UBI: good PEBs: 1024, bad PEBs: 0, corrupted PEBs: 0
[    2.237000] UBI: user volume: 12, internal volumes: 1, max. volumes count: 128
[    2.245000] UBI: max/mean erase counter: 2605/1487, WL threshold: 4096, image sequence number: 1276936678
[    2.254000] UBI: available PEBs: 462, total reserved PEBs: 562, PEBs reserved for bad PEB handling: 20
[    2.265000] UBI: background thread "ubi_bgt0d" started, PID 297
[    2.385000] devtmpfs: mounted
[    2.423000] VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
[    2.455000] devtmpfs: mounted
[    2.464000] Freeing unused kernel memory: 292K
[    6.457000] devpts: called with bogus options
Starting syslogd: OK
Starting klogd: OK
Running sysctl: OK
!!! IMPORTANT !!!
Couldn't determine board model, THINGS WILL BE BROKEN. model=, product= please open an issue on github.com/halmartin/meraki-builder
!!! IMPORTANT !!!
[   38.341000] random: nonblocking pool is initialized
insmod: ERROR: could not load module /lib/modules//vtss_core.ko: No such file or directory
Loaded 'proclikefs.ko'
[   44.426000] click: starting router thread pid 433 (86c79200)
Loaded 'merakiclick.ko'
[   55.560000] elts_meraki: module license 'unspecified' taints kernel.
[   55.567000] Disabling lock debugging due to kernel taint
Loaded 'elts_meraki.ko'
insmod: ERROR: could not load module /lib/modules//vc_click.ko: No such file or directory
[   57.739000] unsatisfied requirement 'vc_click'
[   57.744000] click-config/switch/io-real/vitesse.click:26: unknown element class 'ToVitesse'
[   57.753000] click-config/switch/io-real/vitesse.click:31: unknown element class 'FromVitesse'
[   57.764000] click-config/switch/io-real/vitesse.click:59: unknown element class 'VitesseController'
[   58.092000] click-config/switch.template:74: While configuring 'switch_intf_table :: SwitchIntfTable':
[   58.102000]   SWITCH_HARDWARE: element type mismatch, expected SwitchHardwareIntf
[   58.112000] click-config/switch.template:1045: While configuring 'switch_port_table :: SwitchPortTable':
[   58.122000]   SWITCH_HARDWARE_INTERFACE: element type mismatch, expected SwitchHardwareIntf
[   58.153000] click-config/switch.template:58: While configuring 'l3_update_hardware :: UpdateHardwareTable':
[   58.163000]   SWITCH_HARDWARE_INTERFACE: element type mismatch, expected SwitchHardwareIntf
[   58.181000] click-config/switch.template:383: While configuring 'switch_rpc_server :: SwitchRPCServer':
[   58.191000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.201000] click-config/switch.template:566: While configuring 'CheckStackMaster@187 :: CheckStackMaster':
[   58.211000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.220000] click-config/switch.template:602: While configuring 'CheckStackMaster@235 :: CheckStackMaster':
[   58.230000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.238000] click-config/switch.template:633: While configuring 'switch_mrt :: MulticastRoutingTable':
[   58.248000]   SWITCH_HARDWARE_INTERFACE: element type mismatch, expected SwitchHardwareIntf
[   58.259000] click-config/switch.template:655: While configuring 'ospf_hello_inspector :: OspfHelloInspector':
[   58.269000]   SWITCH_HARDWARE_INTERFACE: element type mismatch, expected SwitchHardwareIntf
[   58.301000] click-config/switch.template:875: While configuring 'msstp_encap_inst :: MSSTPEncap':
[   58.310000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.322000] click-config/switch.template:930: While configuring 'IntraStackResolver@527 :: IntraStackResolver':
[   58.333000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.344000] click-config/switch.template:1072: While configuring 'igmp_table :: IGMPSnoopTable':
[   58.353000]   SWITCH_HARDWARE_INTERFACE: element type mismatch, expected SwitchHardwareIntf
[   58.363000] click-config/switch.template:1093: While configuring 'mld_table :: MLDSnoopTable':
[   58.372000]   SWITCH_HARDWARE_INTERFACE: element type mismatch, expected SwitchHardwareIntf
[   58.382000] click-config/switch.template:1125: While configuring 'msstp_decap :: MSSTPDecap':
[   58.391000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.404000] click-config/switch.template:1187: While configuring 'CheckStackMaster@664 :: CheckStackMaster':
[   58.414000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.422000] click-config/switch.template:1189: While configuring 'CheckStackMaster@669 :: CheckStackMaster':
[   58.432000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.439000] click-config/switch.template:1199: While configuring 'CheckStackMaster@680 :: CheckStackMaster':
[   58.449000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.457000] click-config/switch.template:1212: While configuring 'CheckStackMaster@693 :: CheckStackMaster':
[   58.467000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.476000] click-config/switch.template:1238: While configuring 'CheckStackMaster@726 :: CheckStackMaster':
[   58.486000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.498000] click-config/switch.template:1307: While configuring 'stp_check_master :: CheckStackMaster':
[   58.508000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.515000] click-config/switch.template:1320: While configuring 'lacp_check_master :: CheckStackMaster':
[   58.525000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.534000] click-config/switch.template:1409: While configuring 'udld :: UDLD':
[   58.542000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.551000] click-config/switch.template:1459: While configuring 'CheckStackMaster@861 :: CheckStackMaster':
[   58.561000]   HW_INTF: element type mismatch, expected SwitchHardwareIntf
[   58.650000] Router could not be initialized!
Default port count: 10
net.ipv4.ip_local_reserved_ports = 50000-50127
vc_click isn't loaded; aborting!
/etc/init.d/S11leds: line 8: can't create /click/sw0_ctrl/power_led_orange: nonexistent directory
/etc/init.d/S11leds: line 9: can't create /click/sw0_ctrl/power_led_green: nonexistent directory
Saving random seed: SKIP (read-only file system detected)
Starting network: OK
Starting chrony: Could not open /etc/chrony.conf : No such file or directory
FAIL
Starting dropbear sshd: OK
`

board_data product_number (null)
`
/ # board_data product_number

`

board_data model
`
/ # board_data model
MS320-48
`

**Comment by halmartin** [comment]
@KFDCompiled thank you. The boot output you provided shows that the image you flashed to the switch is from before [1f1af79](https://github.com/halmartin/meraki-builder/commit/1f1af7931524af8b37aa0d49d840bffccadcbc07), so it is no surprise that the MS320 is not correctly detected.

Please flash [postmerkOS-20220406.bin](https://watchmysys.com/files/meraki/ms220/postmerkOS-20220118.bin)

**Comment by KFDCompiled** [comment]
@halmartin the updated firmware correctly autodetected the board!

I corrected the link in the installation instructions--both it and the link in your comment:

> Please flash [postmerkOS-20220406.bin](https://watchmysys.com/files/meraki/ms220/postmerkOS-20220118.bin)

link to 20220118 🤷‍♂️

now i need to try to figure out poe and routing...

**Comment by halmartin** [comment]
> link to 20220118 :man_shrugging: 

Whoops, sorry about that. Corrected my GitHub comment and the installation doc.

> now i need to try to figure out poe

`pd690xx` should work on the MS320, let me know if you encounter any issues.
