### ISSUE TITLE
MS120-24P support

### ISSUE THREAD

**Issue by fenrus** [halmartin/meraki-builder#35]
Hi,

It seems like there is not yet any support for MS120-24P.

I have one of those switches available. Can i assist in getting it supported?

/David

**Comment by halmartin** [comment]
See #11

**Comment by appleeimac** [comment]
Could we possibly change the EEPROM like in the Z3 to bypass secure boot?

**Comment by halmartin** [comment]
The Z3 secure boot bypass exists because the same U-Boot release was used on other devices (MR33, MR30H) with the same ipq40xx SoC that did not ship with secure boot enabled. Meraki could enable secure boot on those devices in the field, there is nothing stopping them, but it would lead to bricked devices and they probably just didn't want to pay to replace failed units.

The MS120 series is based on the Marvell AlleyCat3 ASIC, completely different from the Vitesse ASIC used in the MS220 series. The vulnerable code path is in the `do_meraki_qca_boot` function, which doesn't exist on this platform because it's not a Qualcomm SoC.

There is no code path in U-Boot on the MS120 to disable signature validation based on the model number in the EEPROM.

Please do not necrobump closed issues. If there was a secure boot bypass for this device, I would not be telling people 4 years later it still isn't supported.

tl;dr - No.
